name: Continuous Integration 

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - uses: actions/checkout@v5
      with:
        repository: "https://github.com/Pencilcaseman/AdventOfCodeInputs.git"
        path: "input"

    - name: Install Rust Nightly
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: nightly
        components: rustfmt, clippy

    - name: Install CodSpeed
      run: cargo install cargo-codspeed

    - run: cargo build
    - run: cargo build --release

    - run: cargo test
    - run: cargo test --release

    - run: cargo bench

    - name: Build Benchmarks
      run: cargo codspeed build

    - name: Run Benchmarks
      uses: CodSpeedHQ/action@v4
      with:
        mode: instrumentation
        run: cargo codspeed run
        token: ${{ secrets.CODSPEED_TOKEN }}

